Repository ykyki/extop-tex, pull requests merged in 2021-11, with the labels that each got.

#78 差分表示つきのレヴュー用PDFを作成できるようにする
  documents/catalog/common-preamble.sty
  tools/build-latexdiff.sh
  tools/extopy/src/core.py
  tools/extopy/src/git.py
Labels: 11-create

#72 073 connected spaces
  documents/catalog/theories/connected-spaces.tex
  documents/catalog/theories/path-connected-spaces.tex
Labels: 13-update, 21-math

#75 完全写像の逆像でパラコンパクトが保たれることの証明など
  documents/catalog/chapter-basics.tex
  documents/catalog/list-commands-table.tex
  documents/catalog/theories/closed-maps.tex
  documents/catalog/theories/paracompact-spaces.tex
  documents/config/global-commands.sty
  products/list-commands-table.pdf
Labels: 13-update, 21-math

#86 プルリクテンプレート更新確認用テスト
  README.md
Labels: 24-tool, 25-document
