Repository ykyki/extop-tex, pull requests merged in 2022-04, with the labels that each got.

#94 k-空間のセクションを新規追加
  documents/bibliography/miscellaneous.bib
  documents/bibliography/papers.bib
  documents/catalog/chapter-compactness.tex
  documents/catalog/theories/Hausdorff-like-properties.tex
  documents/catalog/theories/k-spaces.tex
  documents/catalog/theories/pseudo-compact-spaces.tex
Labels: 11-create, 21-math

#115 グローバルコマンド\mapsetfamily, \mapinvsetfamilyの追加
  documents/catalog/list-commands-table.tex
  documents/config/global-commands.sty
  products/list-commands-table.pdf
Labels: 13-update

#114 性質の保存の定義を追加
  documents/catalog/chapter-basics.tex
  documents/catalog/theories/preservation-of-properties.tex
Labels: 11-create

#129 GitHub Actionsでビルドするzipファイルの内容修正
  .github/workflows/build.yml
Labels: 12-fix, 24-tool

#132 連結成分に関する記述を追加
  documents/catalog/theories/connected-spaces.tex
Labels: 21-math

#125 chktexのルール検討
  .chktexrc
Labels: 24-tool

#136 プルリクテンプレートの更新
  .github/pull_request_template.md
Labels: 24-tool
