Repository ykyki/extop-tex, pull requests merged in 2022-07, with the labels that each got.

#149 境界の定義とグローバルコマンドの追加
  documents/catalog/chapter-basics.tex
  documents/catalog/list-commands-table.tex
  documents/catalog/theories/boundaries.tex
  documents/config/global-commands.sty
  products/list-commands-table.pdf
Labels: 23-config

#156 `\topbry` → `\topbd` に統一する
  documents/catalog/theories/connected-spaces.tex
  documents/config/global-commands.sty
Labels: 22-format

#158 Update compare.yml
  .github/workflows/compare.yml
Labels: 24-tool

#159 Update build.yml
  .github/workflows/build.yml
Labels: 24-tool

#160 Update build.yml
  .github/workflows/build.yml
Labels: 24-tool

#157 Engelking演習問題セミナー用のディレクトリとreadmeの作成
  documents/engelking/readme.md
Labels: 25-document
