Repository ykyki/extop-tex, pull requests merged in 2022-01, with the labels that each got.

#84 Feature/079 closed maps
  documents/catalog/theories/Hausdorff-like-properties.tex
  documents/catalog/theories/closed-maps.tex
  documents/catalog/theories/continuous-maps.tex
Labels: 11-create, 13-update

#97 リバイス進行順序の改善
  .github/pull_request_template.md
Labels: 13-update, 24-tool

#95 可算性に関する章とセクションの追加
  documents/catalog/chapter-countability.tex
  documents/catalog/root.tex
  documents/catalog/theories/Frechet-spaces.tex
  documents/catalog/theories/countable-chain-condition.tex
  documents/catalog/theories/first-countable-spaces.tex
  documents/catalog/theories/second-countable-spaces.tex
  documents/catalog/theories/separable-spaces.tex
  documents/catalog/theories/sequential-spaces.tex
  documents/catalog/theories/strongly-Frechet-spaces.tex
Labels: 11-create, 21-math

#103 マニュアルを全体的に更新
  documents/catalog/manual.md
Labels: 13-update, 25-document
